#ifndef BITMASKS_H
#define BITMASKS_H

#define BITMASK_LOWER_32_BITS 0xFFFFFFFFULL
#define BITMASK_LOWER_16_BITS 0xFFFFULL
#define MASK_SIMM9 0x1FF
#define OFFSET_SIMM9 2
#define EXPECTED_REGISTER_OFFSET 0x81A
#define MASK_REGISTER_OFFSET 0x83F
#define EXPECTED_PRE_POST_INDEXED 0x001
#define MASK_PRE_POST_INDEXED 0x801
#define MASK_I 0x01
#define OFFSET_I 1
#define BITMASK_LOWER_12_BITS 0xFFF
#define BITMASK_LOWER_5_BITS 0x1F

#endif
